export const FETCH_NOTES = "FETCH_NOTES";
export const FETCH_NOTES_FULFILLED = "FETCH_NOTES_FULFILLED";
export const FETCH_NOTES_REJECTED = "FETCH_NOTES_REJECTED";

export const FETCH_ADD_NOTE = "FETCH_ADD_NOTE";
export const FETCH_ADD_NOTE_FULFILLED = "FETCH_ADD_NOTE_FULFILLED";
export const FETCH_ADD_NOTE_REJECTED = "FETCH_ADD_NOTE_REJECTED";
